#!/bin/sh
# Xsetup - run as root before the login dialog appears

primary="DP-0"
secondary="DP-2"

xrandr --output "$primary" --primary --mode 3840x2160 --rotate normal --rate 144 --scale 0.75
xrandr --output "$secondary" --off # --noprimary --left-of "$primary" --mode 2560x1440 --rotate left --rate 144
